GET http://localhost:4004/odata/v4/catalog/$metadata

GET http://localhost:4004/odata/v4/catalog/Books

POST http://localhost:4004/odata/v4/catalog/Books 
Content-Type: application/json 
{

"ID" : "1" ,
"title"  : "1" ,
"stock"  : "1" 

}


